spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management_system
    username: root
    password: happy123
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.uml.funfitness.pojo